### ISSUE TITLE
Persistent identity

### ISSUE THREAD

**Issue by WyriHaximus** [leunamnauj/kubernetes-zerotier-bridge#3]
First of all, thank you for putting this together.

Due to Kubernetes nature, a pod can die at any moment. And every time it comes back up a new member joins a network. Add chaoskube to the mix and you can have several new members a day.

Could you help to figure this out, or would you be open for a PR adding this?

**Comment by leunamnauj** [comment]
Hey @WyriHaximus, a PR is always welcome.
About pod dying, you're right. The idea here is to bridge the whole cluster, I've been working on a DaemonSet approach (perhaps +pv).
I'll be publishing in the next couple of days.
Cheers

**Comment by WyriHaximus** [comment]
Hey @leunamnauj of course, this is also why I'm asking if you'd be working on that already as I rather wait a bit longer :).

Personally I'm using a single pod with an additional process in it that proxies TCP connections in and out of the cluster to specific ports.

Don't understand how to bridge the whole cluster with zerotier, and not sure I want to in my case. But I'm looking forward to your approach :+1: . Also have the PV in mind to keep the state persistent but haven't had time to do it yet.

**Comment by leunamnauj** [comment]
Just uploaded the update. I hope it helps

**Comment by WyriHaximus** [comment]
Thanks had a look at it a while ago. Did something similar, but used a secret instead of a config map, and used a stateful set. Working really well <3
