### ISSUE TITLE
How are you using this?

### ISSUE THREAD

**Issue by isaacpz** [leunamnauj/kubernetes-zerotier-bridge#4]
Hi,

Can you explain a bit about how you're using this software?

The readme says that it allows me to access "non-public k8s services", but it looks to me like it just gives zero tier access to the pod hosting the service – not the entire cluster. How are you getting access to other internal Kubernetes services from the single IP that is exposed?

Thanks

**Comment by leunamnauj** [comment]
Hi @isaacpz
The project has been evolving but the idea is to use this solution as a bridge to access to your underlying network and eventually access to your k8s services without expose it to internet.
I hope it helps
