### ISSUE TITLE
unknown field "imagePullPolicy" in io.k8s.api.apps.v1.DaemonSetSpec

### ISSUE THREAD

**Issue by haakonstorm** [leunamnauj/kubernetes-zerotier-bridge#6]
# unknown field "imagePullPolicy" in io.k8s.api.apps.v1.DaemonSetSpec

cloned repo, added values for my persistent storage (freeNAS), and used helm to deploy:

```
helm install kubernetes-zerotier-bridge kubernetes-zerotier-bridge/kubernetes-zerotier-bridge -f charts/kubernetes-zerotier-bridge/values.yaml
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(DaemonSet.spec): unknown field "imagePullPolicy" in io.k8s.api.apps.v1.DaemonSetSpec
```

Googling, is this on the right path?
`https://github.com/kubernetes/kubernetes/issues/75436`

Would love to get zerotier up and running on my setup!

BTW I'm running my cluster on 5 x ODROID N2, that is arm64. Should be good, no?

**Comment by ayushin** [comment]
same issue here on Digital Ocean

**Comment by ayushin** [comment]
fix: 

https://github.com/leunamnauj/kubernetes-zerotier-bridge/pull/7

**Comment by leunamnauj** [comment]
Thanks a lot
