### ISSUE TITLE
provide an example of zerotier configuration to connect pods across two clusters

### ISSUE THREAD

**Issue by ayushin** [leunamnauj/kubernetes-zerotier-bridge#8]

**Comment by ayushin** [comment]
My question is this: I am able to install the pod on every node and connect to the zerotier network, but how do i make the zerotier network/routes available to other pods on the same node?

I tried playing with the different settings but ran out of time.

Any example of how to set it up would be very helpful

@leunamnauj

**Comment by leunamnauj** [comment]
The objective of this project is to provide routed access to the network where k8s cluster lives.
I'm working on a big update and will rewrite the readme with more details.

**Comment by ayushin** [comment]
Right, I am able to access the pod from outside and access outside (zt network) from the pod, but not from other pods on the cluster.
